### ISSUE TITLE
Preflight requests

### ISSUE THREAD

**Issue by danielwegener** [chrisdeely/ForceCORS#13]
Hi there, first of all thanks for this nice extension. 

I have some problems whitelisting non trivial cors requests that trigger cors preflights (to name it, GET with a `range` header).

The problem is, that the remote endpoint does not support CORS at all an responds to those OPTION requests with 501 (not implemented). I tried to dig into the web request api (https://developer.chrome.com/extensions/webRequest) but there seem to be no option to intercept `onErrorOccured` nor to create synthetic responses in `onBeforeRequest`. Before giving up, I wanted to ask If you have an idea to solve this.

**Comment by chrisdeely** [comment]
I'm afraid that I don't know a way around an explicitly negative response to an OPTIONS call. You may be better off writing a proxy server to redirect the calls without respecting CORS at all. But unfortunately that isn't something this extension will be able to do.

**Comment by danielwegener** [comment]
@chrisdeely Aight, I expected that. Thanks anyway.
