### ISSUE TITLE
Why doesn't Chrome DevTools show the updated response headers?

### ISSUE THREAD

**Issue by tony19** [chrisdeely/ForceCORS#15]
ForceCORS properly updates my response headers, but for some reason, DevTools doesn't show the new header values. Why does it show the original values instead of the modified ones? Is there a way to change that?

I added a localhost rule to insert `Access-Control-Expose-Headers` for a custom header. The server sends `Access-Control-Expose-Headers: *` (which apparently doesn't work, hence the need to override the header), which ForceCORS overwrites with my customization.

### Environment
 * Chrome 55
 * macOS Sierra

**Comment by chrisdeely** [comment]
Unfortunately, no. There is an existing Chrome bug for this, but I do not
have a link at the moment

**Comment by tony19** [comment]
Gotcha. Thanks
