### ISSUE TITLE
Chrome web store?

### ISSUE THREAD

**Issue by LaurensRietveld** [chrisdeely/ForceCORS#4]
Hi Chris,

Thanks for you plugin. This one looks particularly interesting, as it uses whitelists. Is there a reason you havent added this to the chrome web store?
I would like to advice this to users of my web application (see http://yasgui.laurensrietveld.nl) as a workaround for some issues they may encounter.
However, I'd like to keep these workaround as easy as possible, meaning I would like to avoid the need to use developer tools

Best, Laurens

**Comment by chrisdeely** [comment]
Hi Laurens,
I'm glad you like the extension. I thought of packaging it for the store, but I haven't spent the time to get it ready.  I'll leave this open as a reminder.  

I'm not sure I'd recommend this for users of a production application though... do you not have control over the services that you are using there? It would be more appropriate to enable CORS directly in the services if possible.

**Comment by LaurensRietveld** [comment]
Ah, great that this is on the todo list. 

I know that using this in a production environment is pretty ugly. However, I'm facing the following problems/requirements:
- Some localhost SPARQL endpoints (i.e. services) users use via my application do not support cors, and have no simple configuration file to enable cors
- Quite some users are unfamiliar with setting up apache, or running a CORS-proxy on localhost (such as the node-js proxy)
- All other options to enable access to these SPARQL endpoints require quite some effort from the users side (something I'd like to avoid)

This is why I particularly like your extension, as this only comprimises a part of the security (using the whitelist), instead of enabling CORS for -all- traffic.

**Comment by Flyingmana** [comment]
There is already a "similar" extension in the store https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi

but your extensions seems a lot better as it uses whitelists
It would be great to have your extension on the webstore too.

**Comment by AshKyd** [comment]
Hey @chrisdeely, great work on this! It's saved me a lot of time.

What's needed to get this ready for the web store in your opinion? I'd be happy to lend a hand.

**Comment by chrisdeely** [comment]
Well, a nifty logo for one :)

**Comment by chrisdeely** [comment]
ForceCORS is now live in the web store: https://chrome.google.com/webstore/detail/forcecors/oajaiobpeddomajelicdlnkeegnepbin?hl=en&gl=US

Thanks for the interest!

**Comment by AshKyd** [comment]
Too good. :)
