### ISSUE TITLE
It doesn't work for me.

### ISSUE THREAD

**Issue by joejeet** [chrisdeely/ForceCORS#8]
This is what I've given: 

URL : http://localhost:3002/*

*Header: Access-Control-Allow-Origin

*Value : http://localhost:3003/

**Comment by chrisdeely** [comment]
I believe the value should only contain the "host" so try "localhost"
instead.

**Comment by chrisdeely** [comment]
@joejeet any luck?

**Comment by joejeet** [comment]
Thanks, Yes it did, it looks like when you try in between with local env it is just "localhost". If you use external to localhost you need to give "http://localhost:port" without slash.

**Comment by artemis15** [comment]
its not working for me
